# Setup
title: Siru Zhang
description: A Simple Homepage
url: https://siruzhang.github.io
# avatar: /avatar.jpeg
paginate: 5
permalink: pretty
# cover_image: /bg.jpeg

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
